[package]
name = "isabelle-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.23"
tracing-subscriber = "0.3"
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
poise = "0.6.1"
